name: Module Resolution
description: Report a problem with module resolution
title: Module Resolution:
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Module resolution can be difficult to configure correctly.
        Be sure you've read the docs thoroughly before filling out this form.
        Most module resolution "bugs" are actually misconfigurations.
  - type: textarea
    id: config
    attributes:
      label: tsconfig
      description: Run `tsc --showConfig` and paste the output here. |
                   Repros that depend on running within external tools (yarn, pnpm, esbuild, etc.) are not TypeScript defects and will not be investigated.
      placeholder:
    validations:
      required: true
  - type: textarea
    id: code-sample
    attributes:
      label: Please provide a self-contained code sample that demonstrates the problem
      placeholder: let greeting = "Hello, world";
      value: "code"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen, and why?
      placeholder: No typechecking errors
      value: "expected"
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: What actually happened instead?
      placeholder: Error on line 3
      value: "actual"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Did this behavior change at a particular version?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
