name: Module Resolution
description: Report a problem with module resolution
title: "Module Resolution:"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Module resolution can be difficult to configure correctly.
        Be sure you've read the docs thoroughly before filling out this form.
        Most module resolution bug reports are actually misconfigurations.
        Let's make sure you're ready to file a module resolution bug.

  - type: markdown
    attributes:
      value: |
        A module resolution bug requires five things:
        1. A module that's trying to import some target module
        2. That target module
        3. The configuration of the importing module
        4. The configuration of the target module
        5. A difference in runtime behavior

  - type: dropdown
    id: defect-kind
    attributes:
      label: Which of the following problems are you reporting?
      options:
        - The module specifier resolves at runtime, but not at build time
        - The module specifier resolves at build time, but shouldn't because it doesn't at runtime
        - The module specifier resolves, but to the wrong file
        - The module specifier resolves to the right file, but something about the types are wrong
        - Something else more complicated which I'll explain in more detail
    validations:
      required: true

  - type: textarea
    id: code-proof
    attributes:
      label: Demonstrate the defect described above with a code sample. This should be at most four lines of code.
      placeholder: import * as foo from "./bar"; // Should not resovle
      value: "code"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: tsconfig
      description: Run `tsc --showConfig` and paste the output here. |
                   Repros that depend on running within external tools (yarn, pnpm, esbuild, etc.) are not TypeScript defects and will not be investigated.
      placeholder:
    validations:
      required: true

  - type: textarea
    id: traceResolution
    attributes:
      label: tsconfig
      description: Run `tsc --traceResolution` and paste the output here.
      placeholder:
    validations:
      required: true

  - type: textarea
    id: import-package-json
    attributes:
      label: Paste the `package.json` of the *importing* module, if it exists
      placeholder: { }
      value: "code"
    validations:
      required: true

  - type: textarea
    id: export-package-json
    attributes:
      label: Paste the `package.json` of the *target* module, if it exists
      placeholder: { }
      value: "code"
    validations:
      required: true
