name: Bug Form-Based
description: Report a defect
title: ""
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for providing your feedback! To help us out, please make sure you've checked
        the FAQ, especially Common Bugs That Aren't Bugs.
  - type: input
    id: search
    attributes:
      label: Search Terms
      description: What search terms did you use when searching for duplicates? Putting these terms here will help future filers find this issue.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: code-sample
    attributes:
      label: Please provide a self-contained code sample that demonstrates the problem
      placeholder: let greeting = "Hello, world";
      value: ""
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen, and why?
      placeholder: No typechecking errors
      value: ""
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: What actually happened instead?
      placeholder: Error on line 3
      value: ""
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Did this behavior change at a particular version?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
